image: Visual Studio 2015
branches:
  except:
    - gh-pages

skip_commits:
  message: /\[skip appveyor\]/

environment:
  gsu_json:
    secure: E9Gwz/ovMP5T9LFpf0kXQjM739m2sYgPc3qm8WmSnjFmU82FSOuAn3RcLTDIfOHttFSzmuXmEsF9SI185rV+2Cksq9vDUiLCuTT2ujX8YSwn6sWSJENgbUHoxgykKeDf1h7tkgO5y7dX9EC6qXvPJWEjMaCFeQmcoBuZX1nUnWke5ygE/6EaPf28PH5HTgp2qxYgNmjs+LQxgarK+6EbvjtdUQWCajn2SjJUUbZtJ0IW/PMzJQ0ZfX2Dx4qz173YQmYA76AI/axKTUpHUI89vGfT+ifGr8Abia9HNdBpl76fTQ9R4QV0HFb6Fu+T70YxVzMZY3zdl+vILXw7UqP2LiWzd5DUrfcYT32pY4c8oBlNvmxUUZw7zBdnUapUptZPo+7nleqtP1L6jG5Pq2daFlC7/WkaxPxyW5BTgIx9wklufjeO9IG61BIiyeHZmtbk/n/THwGEBwpp4ClfDuMcaSZyECjr6tn9KxR2qg02ZT6M9iP1zN4MyeXEK5I5crKjnGbvxZR0jHWfomnB1TqXo4vg3Kiya317SniGDWn/2oa8FI/rvQaW1omJXmj4gWWs2Q9nwKYl2g8mwaDeJC3bsuziP6Kzaf1hrhLnVAFkELgIo+DMe7bMBCL+O5q0rHu18pm66DaUnO3hUHI0cnKr+bluhRz/gQyhqDgG2MNZGmM+XKljloS2oV8rsH9DipIuSdKBci0Dg3I2a8uokGZb0o/f80KnUv87k+sqSSF0NiVlQqjkzuTEf8n1K5XgW7UDKc2yt9c69PISGqdqE3SOhK0lHW2FvPHrccbfdBlngpgyigBIGLfpuRoThNYf2HLsOPGa83nmSK+bl/F1RjAdVNvqLGLj68IoVLv6kvG2odHhuwdvvwWuyiR3BQraKtkf+y4EftmTjwDyUKxK83HzQq/fM36I+r+rjJ+m+Th4DROSIgHoxN5QzSv1sao+qyZ/r9+UXYeN/Pd8u6o5bED9+4w33Qcdv85aDaELGFWtJM8A/5BcBBUjHRJHxowX2ipN4Y+NQusHtjCzhNG9WQfEcqKzI2SCyDs7YYtbqI2Cs8pzkbv116hMlofma/6Lv7F6/AQxkNZZdVoQwMzVHjV5sOGD2ev+jM2zd4XeGXvWY0NPuG6PhZ1yA/t5xz/x7EpL/8syrBFf94wwApN10frsBnbc3JtTw/To4HGPbRtQu0c+huPj8RBAoIbvx9Djtabg9cb/NhruBxN7BLwUe8zRuBdNxVCQS3V5+Gqz+OtE46YVOViS/C+zFRxyUlY2PtfUfUawTsVBI6MQcls7zK5MbNPhnC6guyeBFspc/T2a3yYxh9u4Ae53W1c253fxLfYJOfEX6+/KlIqr+dwBIXk/HBtMphF9WUQ94JROxfoAM30Eh/xyls2Y7KBhnrQqwVevCwEWb0r36mAWNhcLahJ5pjZIkmUHovctcBz3b4L6o6oLcRs+caVnRhCYTQ6UAqxIVW7s3q7aLEnHOyeRiTDf4S7F/69LIHIPupTljapbs5NhVEwuKM1JWAMTSVSJ+Pn9/UaaIUDJsogsk6JHvVmrCSJGj+B+bqH8YHnauPnKOflpVr0luv7Gb2sBh96mRTtTlI5UW0LDUjHThX+EXgyE8X2OxEt7YCtI+YQz5nJXgIXskIC+YWy4tJg0ORWVqsyYjw5k5AZjucgDnnYktunzXecGnbDvV0eEDyg3MOXg0GOvjWSlVMIKHOQKSC/AP1pi428/dAuVTTh3BWhS/3K8NNC6NhTH3Jru51lkr0dws8J1xxhEscaK1rif+K98hMi5W0eYOipu3UIlayJvebKTxpA9m4MqP1kTLYFDrGZhE8OL7FWdmwE9GOn5MHV7S5BwtDIiMqdJee7JRuqSLC1gklQORA7F5HS+M7Kc3nCfUnLAAcwOeLZOi/K/B0OzfL+X37zdIMJCb80Fx+27GkgaCev/AiM6lZUHgrv3iT95C1UIgLL0sqwXWjCMCza+tqcpDO2B5YvLQGmErMASCz+CyI2NIjCSa0PWAjWlDul/zUSg3q2QupZ3ynL5Rkdqakw1Bf/aXgksehpj+6xPeSLgkdU8JDoeLuHFIBfbHjOsVaD0S7XRu8JmxOgLDaaE6GlcqEep6I/Q/t1GZ4K8R2P8qLpmugSU/Zt6NitBhQrHAWTA86nGdsuvLti6kuoet+dpq03wl6uKIXSs3Lu5e7hdEw8Ec/qqeELhxTasNO1rrPcXFisB7hiWzXN1pcpFe/IAd8RrsGqcl5PASxKsj89pgkmoBH9TQxgSn4QCJ/x7cMvG+carbvNMCwMVEZIy6Gi+tPBnP5wiYcBLwOZQWmVjKIZXHNcFCbZMARkdiQ2OuNqTc8vAulLnyz4jXcVkbnFgQqxxQ5MAp/sYgSG8PfKlbkwkcDzE/WFClTcioNijdpEJewKKX5JJT0TDzT5QiAtxf8tH652An7aij2QU3bSJQaOQBRVAuWnQlxvC6jDusE49AlXoVUe+9of7W67xi24lGoxoXm/laDcYeJSThaS+MyJhmNF6M/CpbDeT4KBt4o2ZvDdaPG+5EHtCilFvoj64IDU8MFWLeWaLAL4AQ7N4O8n+L/Y2TtBJdBX3qvD9XRYVo+mXhpjnIRi8BhabexW4LV/ScRLxfRVzfkQplMgMXYORV6zTdZN1/KuBfdkAi633+NrVZmMV0eLu/5dhJXwHrsQJsEDcL4yXyxbieOTdt4py3SCk/EUQUKHeOvjlqJkKtO8NbDTfLkzbWddJYOfXPP2jrQmvelZLtzuuxXeFLShU3hRE/GKs3Vy5OyTrBZ5p8AknPVgaeMUZ+tSZKAE09+dTFqwa4X6XXSeTVGTm5t6uIhRXGOJPO7zrOhh0NGAqa2hPfG1L0xDSf1znK81ZRl4VG5t4bG6RpKJ3CujctbEJUZQhzKY87gjdmLPfi/BN69K0x3mi5ai8VA0Kn4+/AIj9K+Z0otIDbOlTFr0oMoacJRReaeOhT8Qf9nnroDZpxNQopKaTfctc9MiDswfo6csw91nrzD9u09KioytCCraAruwEyhlFeSNpgj/4jdhb4J2o/ebX5mywJFNAsGkQwq6rPKH0DJrROBBGZ7OgjGWcQGoMHylRnO4krKqVLoWAaoHST9Uop6dlGksteclXNgVP4eoB3zVG/BlUfMxg+XGedsMbQPLSuxCAPIddhVqfpxKDzQHJnvOCEmCajgEFwpQYVuuey7LTeMZFzXEI2TXOiVlyWUbpKt9RheE1AtFTM07f2Z98dd+fWb6+w+/6M5sIAegZNaHLfQSRNz1QNd7H65cDCwGBMQhGqs9Tbe6WvHj41d4CqS/ugC+CgYV8AsSAVgB6mCEywLdXHcCfS+7ZHf1a68giUuw2ie9ljUlBVwMXnkrRk6y+Py0zMtnxYHhWBFFhzjNflwTpPsBSgVj/2/EtAG4XWnbAoLXyw4ZLCOWaRavQg/ngXm6nD5riXfyDNL45kKwRhJDWVP8pWK83yOe+eb4opmOxryKL8uqMB6HFfNq6AKE0U29GT+5QWxIb8+pl58difRY9F1Ug6CmBAMmF083mOqzua0CHwPu6x4n610lb/0uf+MP67FyXl63x3wqHIfI64qhUFEyuHJK8IGteMdTyMthfB0oiDIwrm/zg/CYp43Br+gyRbGgApRG/zfLuzcoNUCU4C0jL1clz42FTWmHXwybTbuiZv8ItNjxFdI8+hNzouBJUUTwlU7qpyuqSBkyqOgcWhjSbf70X3PuH+xirwjHVxbKCyEXndJe2nWdfwa765P8ow3NkhzEORRmcWAHarqApsyrlEZQ6ga3LsnXLz4Fpw0hxE/5HpF+s6wBm9rtPQZd4FjxLrnk7igJyGyut6wh3l/4qE+B/Yvb/9nbfh49LWhq01KCxZK144xjhq+mLwIwBOLEMgz/iXYEGa6oiebM/wxA2qHnW5J+KyuR80kPbTcojaUepok8u8AHcNUHaWeuscbniGz9IC3w7mNidOieE/uyCwGYUykEWhG7EVMvNVbSooR68z8vsC3nisE70E9751F/jkJGljEzmRRKircD7pHbEEWzRqwJQlLXia9fXnsoKB8fnaFQ/wj3qmFzSBRgm9FvlHoTyalHy+iuqQeoui4Xtis2En0iQc+rFiDDLAqcZehU=

install:
  - set QTDIR=C:\Qt\5.11.3\mingw53_32
  - ps: $exePath = "$($env:USERPROFILE)\nsis-2.46-setup.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('http://ufpr.dl.sourceforge.net/project/nsis/NSIS%202/2.46/nsis-2.46-setup.exe', $exePath)
  - ps: cmd /c start /wait $exePath /S /D=C:\nsis
  - set PATH=C:\nsis;C:\MinGW\bin;%QTDIR%/bin;%PATH%
  - ps: >-
      $zipPath = "$env:APPVEYOR_BUILD_FOLDER\gsutil.zip"

      $gsutilPath = "$env:APPVEYOR_BUILD_FOLDER"

      (New-Object System.Net.WebClient).DownloadFile('https://pub.storage.googleapis.com/gsutil.zip', $zipPath)

      7z x $zipPath -y | Out-Null
      
      $bytes = [System.Convert]::FromBase64String($env:gsu_json)
          
      [System.IO.File]::WriteAllBytes("$env:USERPROFILE\service.json", $bytes)  

before_build:
  - cd src

build_script:
  # - sed -i "QMAKE_CXXFLAGS += -std=c++0x"/"QT += gui"/"QT += core"/"QT += widgets"/"QT += testlib"/"QT += xml"/"DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" PictureCrypt.pro
  # - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" PictureCrypt.pro
  # - qmake "QMAKE_CXXFLAGS += -std=c++0x" "QT += gui" "QT += core" "QT += widgets" "QT += testlib" "QT += xml" "DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x040900" # -r -spec win32-g++
  - cd app
  - qmake.exe C:\projects\picturecrypt\src\app\app.pro -spec win32-g++
  - C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe all
  - C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe clean -j8
  - sh: sh ../scripts/clean.sh

  - cd ..
  - mkdir deploy
  - cd deploy
  - mkdir debug
  - mkdir release
  - copy "C:\projects\picturecrypt\src\app\build\Debug\PictureCrypt.exe" "C:\projects\picturecrypt\src\deploy\debug\PictureCrypt.exe"
  - copy "C:\projects\picturecrypt\src\app\build\Release\PictureCrypt.exe" "C:\projects\picturecrypt\src\deploy\release\PictureCrypt.exe
  - cd debug
  - windeployqt.exe --debug PictureCrypt.exe
  - cd ../release
  - windeployqt.exe --release PictureCrypt.exe
  - copy "%QTDIR%\bin\libstdc++-6.dll" . /y
  - copy "%QTDIR%\bin\libwinpthread-1.dll" . /y
  - cd ../..

  - makensis.exe .\scripts\PictureCrypt.nsi

  - cd console
  - qmake.exe C:\projects\picturecrypt\src\console\console.pro -spec win32-g++
  - C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe
  - tree . -f
  - cd ../deploy
  - mkdir console
  - copy "C:\projects\picturecrypt\src\console\release\picturecrypt.exe" "C:\projects\picturecrypt\src\deploy\console\picturecrypt.exe"
  - cd console
  - windeployqt.exe --release picturecrypt.exe
  - copy "%QTDIR%\bin\libstdc++-6.dll" . /y
  - copy "%QTDIR%\bin\libwinpthread-1.dll" . /y
  - cd ../..

  - makensis.exe .\scripts\PictureCrypt-console.nsi

before_test:
  - cd tests
  - qmake.exe C:\projects\picturecrypt\src\tests\tests.pro -spec win32-g++
  - C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe
  - cd release
  - dir
  - windeployqt.exe --release tests.exe
  - copy "%QTDIR%\bin\libstdc++-6.dll" . /y
  - copy "%QTDIR%\bin\libwinpthread-1.dll" . /y

test_script:
  - .\tests.exe -xunitxml -tickcounter -o testresults.xml

after_test:
    # upload to gcs
  - ps: cd $gsutilPath
  - ps: $artifacts.values | Where-Object { $_.path -like '*.exe' } | ForEach-Object {.\gsutil\gsutil -o "Credentials:gs_service_key_file=$env:USERPROFILE\service.json" cp $_.path gs://waleko-personal.appspot.com}
  - ps: Write-Host "Please ignore NativeCommandError above, this is because gsutil writes output to stdErr" -foregroundcolor Green
    # chocolatey
  - ps: cd C:\projects\picturecrypt\choco
  - ps: cp C:\projects\picturecrypt\src\PictureCrypt-setup.exe .
  - ps: (Get-Content '.\picturecrypt.nuspec' -Raw).Replace("<version>1.0</version>", "<version>$($env:APPVEYOR_BUILD_VERSION)</version>") | Out-File '.\picturecrypt.nuspec'
  - ps: choco pack

artifacts:
  - path: src/deploy/debug
    name: PictureCrypt-debug
  - path: src/deploy/release
    name: PictureCrypt-release
  - path: src/tests
    name: tests
  - path: src/PictureCrypt-setup.exe
    name: setup
  - path: src/deploy/console
    name: console
  - path: src/PictureCrypt-console-setup.exe
    name: console-setup
  - path: choco/*.nupkg
    name: nuget

deploy:
- provider: NuGet
  server: https://push.chocolatey.org
  api_key:
    secure: qCqP5gD9wcT+PU3UtS1cuyndUrjO4q2Ne907JSNt5MW2k5qyKfejqVD4pUQ8YCf+
  artifact: nuget

on_finish:
  # upload test results
  - ps: cd C:\projects\picturecrypt\src\tests\release
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults.xml))
